apiVersion: v1
name: mockserver
version: "5.11.2"
appVersion: "5.11.2"
keywords:
  - mocking
  - mock-server
  - http-mock
  - http
  - test
  - test-server
  - proxy
  - http-proxy
  - socks-proxy
  - https-proxy
